module = "gateway"
[frontend]
#qps limit
qpslimit = 102
#最大客户端连接数字
maxconn = 100000
#slot 槽位数字
slotnum = 200
#黑名单长度
blacklistnum = 10000
#IP地址
ip = "127.0.0.1"
#端口号
port = 9090


[backend]
#qps limit
qpslimit = 102
#最大客户端连接数字
maxconn = 100000
#slot 槽位数字
slotnum = 200
#黑名单长度
blacklistnum = 10000
#IP地址
ip = "127.0.0.1"
#端口号
port = 9091
